### ISSUE TITLE
Deck Tracker Overlay's "Copy Deck Code to Clipboard" feature broken on Twitch?

### ISSUE THREAD

**Issue by MillenniumDH** [HearthSim/twitch-hdt-frontend#51] opened 2020-04-22 18:08 UTC
Using Google Chrome. I didn't really change anything but for the past couple of days I can't copy the deck code by clicking on that copy button on Deck Tracker Overlay when I watch a streamer play HS. Anyone else having a similar problem?

**Comment by beheh** [comment] 2020-04-25 15:53
Moved this to the appropriate repository.

This is due to Chrome's new(?) cross-domain iframe permissions, which it doesn't grant to our extension. I've tried using the permissions API locally to test whether we can request permission, but I haven't had much success. We'll probably have to add a text-based "copy text" fallback like on mobile. In the mean time, you'll need to use another browser instead.

**Comment by beheh** [comment] 2020-04-25 15:53
Duplicate of #50

**Closed as completed by beheh** 2020-04-25 15:53 UTC
